# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 15:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0014_auto_20160318_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backingindex',
            options={'verbose_name_plural': 'backing indexes'},
        ),
        migrations.AddField(
            model_name='backingindex',
            name='backend',
            field=models.CharField(choices=[(b'wheelsproxy.client.PyPIClient', 'PyPI'), (b'wheelsproxy.client.DevPIClient', 'DevPI')], default=b'wheelsproxy.client.PyPIClient', max_length=255),
        ),
        migrations.AlterField(
            model_name='backingindex',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_duration',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_log',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='md5_digest',
            field=models.CharField(blank=True, default=b'', editable=False, max_length=32, verbose_name='MD5 digest'),
        ),
        migrations.AlterField(
            model_name='build',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='original_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
