# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:39
from __future__ import unicode_literals

from django.db import migrations


def migrate_details(apps, schema_editor):
    Release = apps.get_model('wheelsproxy', 'Release')
    releases = Release.objects.filter(original_details__isnull=False)
    for rel in releases.iterator():
        rel.url = rel.original_details['url']
        rel.md5_digest = rel.original_details['md5_digest']
        rel.save(update_fields=['url', 'md5_digest'])


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0016_auto_20160808_2139'),
    ]

    operations = [
        migrations.RunPython(migrate_details),
    ]
