# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0017_auto_20160808_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='original_details',
        ),
    ]
