# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0019_auto_20160810_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledrequirements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='internal_compiled_requirements',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='pip_compilation_status',
            field=models.CharField(choices=[(b'pending', 'Pending'), (b'done', 'Done'), (b'failed', 'Failed')], default=b'pending', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='pip_compiled_requirements',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
