# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 12:11
from __future__ import unicode_literals

from django.db import migrations, utils

from wheelsproxy import models


def normalize_versions(apps, schema_editor):
    Release = apps.get_model('wheelsproxy', 'Release')
    to_delete = []
    for rel in Release.objects.iterator():
        normalized_version = models.normalize_version(rel.version)
        if rel.version != normalized_version:
            rel.version = normalized_version
            try:
                rel.save(update_fields=['version'])
            except utils.IntegrityError as e:
                if 'Key (package_id, version)' in e.message:
                    # Another release with the same normalized version already
                    # exists in the index. pip will every only download the
                    # normalized version and ignore the non-normalized one, so
                    # it is safe to just delete this version.
                    to_delete.append(rel.pk)
    Release.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wheelsproxy', '0020_auto_20160811_1443'),
    ]

    operations = [
        migrations.RunPython(normalize_versions),
    ]
