# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0021_auto_20160812_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiledrequirements',
            name='index_url',
            field=models.URLField(default='https://wheels.aldryn.net/v1/aldryn-extras+pypi/aldryn-baseproject/+simple/'),
            preserve_default=False,
        ),
    ]
