# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import wheelsproxy.models
import wheelsproxy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0022_compiledrequirements_index_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_digest', models.CharField(blank=True, default=b'', editable=False, max_length=32, verbose_name='MD5 digest')),
                ('build', models.FileField(blank=True, max_length=255, null=True, storage=wheelsproxy.storage.dsn_configured_storage(b'BUILDS_STORAGE_DSN'), upload_to=wheelsproxy.models.upload_build_to)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('filesize', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('build_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('build_duration', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('build_log', models.TextField(blank=True, editable=False)),
                ('external_url', models.URLField(max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheelsproxy.Platform')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalbuild',
            unique_together=set([('external_url', 'platform')]),
        ),
    ]
