# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 22:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import wheelsproxy.models
import wheelsproxy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0023_auto_20160815_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='environment',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='backingindex',
            name='backend',
            field=models.CharField(choices=[('wheelsproxy.client.PyPIClient', 'PyPI'), ('wheelsproxy.client.DevPIClient', 'DevPI')], default='wheelsproxy.client.PyPIClient', max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='md5_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='MD5 digest'),
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='internal_compilation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='pip_compilation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='externalbuild',
            name='build',
            field=models.FileField(blank=True, max_length=255, null=True, storage=wheelsproxy.storage.dsn_configured_storage('BUILDS_STORAGE_DSN'), upload_to=wheelsproxy.models.upload_external_build_to),
        ),
        migrations.AlterField(
            model_name='externalbuild',
            name='md5_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='MD5 digest'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='type',
            field=models.CharField(choices=[('docker', 'Docker')], max_length=16),
        ),
        migrations.AlterField(
            model_name='release',
            name='md5_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='MD5 digest'),
        ),
        migrations.AlterField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
    ]
