# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0025_compiledrequirements_index_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiledrequirements',
            name='internal_compilation_log',
            field=models.TextField(blank=True, editable=False, verbose_name='Compilation log'),
        ),
        migrations.AlterField(
            model_name='compiledrequirements',
            name='pip_compilation_log',
            field=models.TextField(blank=True, editable=False, verbose_name='Compilation log'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
