# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0026_auto_20160930_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='setup_commands',
            field=models.TextField(blank=True, default='', help_text='Commands to run before the build if the environment needs to be prepared in a special way. One command per line.'),
        ),
        migrations.AddField(
            model_name='externalbuild',
            name='setup_commands',
            field=models.TextField(blank=True, default='', help_text='Commands to run before the build if the environment needs to be prepared in a special way. One command per line.'),
        ),
    ]
