# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import wheelsproxy.models
import wheelsproxy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsproxy', '0027_auto_20161005_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='default_setup_commands',
            field=models.TextField(blank=True, default='', help_text='Commands to run before the build if the environment needs to be prepared in a special way. One command per line.'),
        ),
        migrations.AlterField(
            model_name='build',
            name='build',
            field=models.FileField(blank=True, max_length=512, null=True, storage=wheelsproxy.storage.dsn_configured_storage('BUILDS_STORAGE_DSN'), upload_to=wheelsproxy.models.upload_build_to),
        ),
    ]
