# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20151105_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
