# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_build_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='original_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
