# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20160318_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='release',
            name='original_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
