# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20160808_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='md5_digest',
            field=models.CharField(blank=True, default=b'', editable=False, max_length=32, verbose_name='MD5 digest'),
        ),
        migrations.AddField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, max_length=255, default=b''),
        ),
        migrations.AlterField(
            model_name='backingindex',
            name='backend',
            field=models.CharField(choices=[(b'index.client.PyPIClient', 'PyPI'), (b'index.client.DevPIClient', 'DevPI')], default=b'index.client.PyPIClient', max_length=255),
        ),
    ]
